[versions]
kotlin = "1.9.22"
ktlint = "12.1.1"
junit = "4.12"
mockk = "1.13.13"
agp = "7.0.0"
gradlePluginPublish = "1.3.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = {group = "io.mockk", name = "mockk", version.ref = "mockk"}
android-tools = {group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = {group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin"}

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }