[versions]
jetbrainsKotlinJvm = "1.9.0"
ktlint = "12.1.1"

[libraries]

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }


